### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by GijsbertH98** [bielcardona/pySunScene#48]
Hey!

When trying to import a PVmaterial

file_Pv = 'Silicon.txt'
otsun.PVMaterial("pv", file_Pv)

raises the error: TypeError: expected string or bytes-like object

Why is this not working? 

Kind regards,
Gijs
[Silicon.txt](https://github.com/bielcardona/OTSun/files/8728932/Silicon.txt)

**Comment by bielcardona** [comment]
It works for me. 

What version of python/FreeCAD/otsun are you using?

**Comment by GijsbertH98** [comment]
I figured it out already! problem with the 

def load_from_txt_or_csv(file):
    df = pd.read_table(
        file,
        sep='\t',
        index_col=0,
        header=None,
        comment='#',
        engine='python'
    ).interpolate(method='index')
    df.insert(0,0,df.index)
    return df.values

where the .txt used the tab as delimiter, the code had: delimiter=none
