### ISSUE TITLE
Webapp

### ISSUE THREAD

**Issue by GijsbertH98** [bielcardona/pySunScene#49]
Hi,

Is the webapp working correctly? It seems to send 0kb output files to the provided mail adress.

Gijs

**Comment by bielcardona** [comment]
Please send us the the identifier of the computation so that we can try to find out what happened.
Cheers!

**Comment by GijsbertH98** [comment]
I cannot find that number anymore! I got the mail with results at wo 22-6-2022 14:35 Amsterdam time

**Comment by bielcardona** [comment]
We could find the log of your computation. The problem with your computation is that you specified a value of 0 for the CSR parameter (and also for the thermal aperture), which should have been left blank. 

Please let us know if you can make it work.

**Comment by GijsbertH98** [comment]
It works, thank you!
