### ISSUE TITLE
Randomness in source

### ISSUE THREAD

**Issue by GijsbertH98** [bielcardona/pySunScene#51]
Hi there,

Is it possible to use the linear random generator in the math.py file? It is marked with #'s at the moment. I would like to use it to emit rays that do not have a totally random x and y coordinates in the emitting region. For example: emitting region of 1m2 with 1.000.000 rays equally distributed per mm2

kind regards,

Gijsbert

**Comment by bielcardona** [comment]
Dear Gijsbert,

In order to do what you want you should subclass `SunWindow` in `source.py` and overide the method `random_point`, where you can implement the logic that you want.

Hope this helps.

Biel
